name: Build Raspbian Bullseye Image

on:
  schedule:
    - cron: "0 6 1 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./bullseye/.
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: fsodano79/raspbian:bullseye-${{ steps.date.outputs.date }}
